### PR TITLE
print null objects as empty string

### PR DESCRIPTION
**Pull request by scottvlaminck**
api gateway prints null objects as empty string, use velocityjs "silence" option to get the same result

Fixes Issue https://github.com/ToQoz/api-gateway-mapping-template/issues/5

### CODE REVIEW

**Comment by ToQoz** [comment]
thank you!

**Comment by scottvlaminck** [comment]
Thanks for merging this! When do you think it would be possible to do another release that could be usable via npm?

**Comment by toqoz** [comment]
@scottvlaminck I've just released v0.0.8.

**Comment by scottvlaminck** [comment]
That’s great. Thanks!

**Pull request merged**
